
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - uses: actions/setup-node@master
    - name: Install node modules
      run: yarn install

    - name: cache gradle wrapper
      run: cd android && gradle wrapper

    - name: Make executable Gradle
      run: cd android && chmod +x ./gradlew  

    - name: build apk
      run: cd android && ./gradlew buildRelease 
   

    # - name: build aab
    #   run: cd android && ./gradlew assemleRelease
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
    # Artifact name
        name: releaseApk
    # A file, directory or wildcard pattern that describes what to upload
        path: android\app\build\outputs\apk\release\app-release.apk
