
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: aaaa

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
#     - name: iOS Build/Release Action
#       # You may pin to the exact commit or the version.
#       # uses: hectorguerrini/build-ios-action@32a06e7b8b78dbd4e9e956bc84d3ee7ec8442130
#       uses: hectorguerrini/build-ios-action@v1.0.4
#       with:
#         # Project path
#         project-path: 
#         # Base64 encoded p12 file (key + cert)
#         p12-base64: 
#         # Base64 encoded mobileprovision file
#         mobileprovision-base64: 
#         # For example, iOS Distribution
#         code-signing-identity: 
#         # Team id
#         team-id: 


    - uses: actions/setup-node@master
    - name: Install node modules
      run: yarn install

    - name: cache gradle wrapper
      run: cd android && gradle wrapper

    - name: Make executable Gradle
      run: cd android && chmod +x ./gradlew  

    - name: build apk
      run: cd android && ./gradlew buildRelease 
   

    # - name: build aab
    #   run: cd android && ./gradlew assemleRelease
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
    # Artifact name
        name: releaseApk
    # A file, directory or wildcard pattern that describes what to upload
        path: android/app/build/outputs/apk/debug/app-debug.apk
